version: '3.8'
services:

  postgres:
    image: postgres
    volumes:
      - postgres_data:/usr/local/pgsql/data
    environment:
      - MYSQL_ROOT_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
